mvvm_demo/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace mvvm_demo.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

mvvm_demo/Models/Profile.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;

namespace mvvm_demo.Models
{
    public class Profile
    {
        public int ID { get; set; }

        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Address { get; set; }
        public List<ProfileDetail> Details { get; set; }

    }

    public class ProfileDetail
    {
        public string Detail { get; set; }
    }
}

mvvm_demo/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using mvvm_demo.Areas.HelpPage.Models;

namespace mvvm_demo.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

mvvm_demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvvm_demo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

mvvm_demo/Controllers/IDIController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace mvvm_demo.Controllers
{
    public class IDIController : Controller
    {
        //
        // GET: /IDI/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /IDI/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /IDI/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /IDI/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /IDI/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /IDI/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /IDI/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /IDI/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

mvvm_demo/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Microsoft.AspNet.SignalR;
using Microsoft.AspNet.SignalR.Hubs;


namespace mvvm_demo.Controllers
{
    public class ProfileController : ApiController
    {

        private static Models.Profile _profile;        
        
        public Models.Profile Get()
        {
            if (_profile == null)
            {
                _profile = new Models.Profile
                {
                    Title = "Mr",
                    Firstname = "Bill",
                    Lastname = "Gates",
                    Address = "1 Main st, Maintown, Maine",
                    Details = new List<Models.ProfileDetail> {
                            new Models.ProfileDetail(){Detail="01 12345678"},
                            new Models.ProfileDetail(){Detail="bill@microsoft.com"},
                            new Models.ProfileDetail(){Detail="Billionaire"}   
                        }
                };
            }   

            lock (_profile)
            {
                return _profile;
            }
        }
        
        public HttpResponseMessage Post([FromBody]string value)
        {
            return Request.CreateResponse(HttpStatusCode.NotImplemented);
        }

        public Models.Profile Put(Models.Profile profile)
        {
            lock (_profile)
            {
                _profile.Address = profile.Address;
                _profile.Details = profile.Details;
                _profile.Firstname = profile.Firstname;
                _profile.Lastname = profile.Lastname;
                _profile.Title = profile.Title;               

                return _profile;
            }
        }

        
        public HttpResponseMessage Delete(int id)
        {
            return Request.CreateResponse(HttpStatusCode.NotImplemented);
        }
    }
}

mvvm_demo/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace mvvm_demo.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IQueryable<string> Get()
        {
            return new string[] { "value1", "value2" }.AsQueryable();
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

mvvm_demo/Views/Home/Index.cshtml
@{
    Layout = null;
}


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Tech Demo [1] - MVVM</title>
    @Styles.Render("~/Content/css")    


    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/knockout-3.0.0.js"></script>

    <script src="~/Scripts/jquery.signalR-1.0.0-rc1.min.js"></script>
    <script src="~/signalr/hubs"></script>

    <script src="~/Scripts/profile.js"></script>
</head>
<body>
    <header>
       <h3>Profile: <span data-bind="text:fullName"></span></h3>
    </header>
    <section>
        <p>Title: <span data-bind="text:title"></span></p>
        <p>Firstname: <span data-bind="text:firstName"></span></p>
        <p>Lastname: <span data-bind="text:lastName"></span></p>
        <p>Address: <span data-bind="text:address"></span></p>
        <div data-bind="visible:details().length >0">Details:
            <ul data-bind="foreach:details">
                <li><span data-bind="text:detail"></span> <a href="#" data-bind="click:remove">remove</a></li>                
            </ul>            
        </div>
        <form data-bind="submit:addDetail" action="#">
                <input type="text" id="txtDetail" data-bind="value:addItemTitle, valueUpdate: 'afterkeydown'" />
                <input type="submit" id="btnAddDetail" value="Add detail" disabled="disabled" data-bind="enable:addItemTitle().length > 0" />
        </form>

        <a href="#" data-bind="click:sendUpdate">Save</a>

    </section>
    <hr />
    <section>
        <p>Title: <input type="text" id="txtEditTitle" data-bind="value:title" /></p>
        <p>Firstname: <input type="text" id="txtEditFirstname" data-bind="value:firstName"/></p>
        <p>Lastname: <input type="text" id="txtEditLastname" data-bind="value:lastName" /></p>
        <p>Address: <input type="text" id="txtEditAddress" data-bind="value:address" /></p>       

    </section>

</body>
</html>

mvvm_demo/Views/IDI/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_IDILayout.cshtml";
}

    <header>
        <h3>IDI - knockout binding and validation</h3>
    </header>
<section>
    <div id="div_root">
        
        <div data-bind="template: {name:'demographic-template',foreach:data}"></div>
        
        <script type="text/html" id="demographic-template">
            <div>
                <h5 data-bind="text:Label"></h5>
                <h6 data-bind="text: Value"></h6>
                
                <input type="text" data-bind="value: Value, enable: Enabled, visible: !IsList()"/>
                <select data-bind="options: ValueList, enable: Enabled, visible:IsList" />
                
            </div>
        </script>
        
    </div>
</section>


@section scripts_bottom
{
    <script lang="javascript">
        'use strict';

        function demographicViewModel() {
            var self = this;

            // custom validation settings 
            self.validationMapping = {
                // property name
                Value: {
                    create: function (options) {
                        return ko.observable(options.data)
                                //.extend({ required: true }) // required is true
                                .extend({  // min length is 3 with custom message
                                    minLength: {
                                        params: 3,
                                        message: "Must have 3 or more characters."
                                    }
                                });
                    }
                }
            };

            self.data = ko.observableArray();

            self.LoadData = function(data) {
                ko.mapping.fromJS(data, self.validationMapping, self.data);
                console.log(self.data);
            };          
            
        }

        //load view-data on page ready
        $(function() {
            var viewModel = new demographicViewModel();
            ko.applyBindings(viewModel);
            $.get("/api/idi", function(item) {

                viewModel.LoadData(item);

            }, "json");
        });

    </script>
}

mvvm_demo/Views/Shared/_IDILayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>Tech Demo [1] - MVVM</title>
    @Styles.Render("~/Content/css")
    
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/knockout-3.0.0.js"></script>
    <script src="~/Scripts/knockout.mapping-latest.js"></script>
    <script src="~/Scripts/knockout.validation.js"></script>
    <script src="~/Scripts/underscore.js"></script>
    @RenderSection("scripts_head", required:false)
</head>
<body>
        @RenderBody()
    
    @RenderSection("scripts_bottom", required:false)
</body>
</html>

mvvm_demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <p class="site-title">
                    <a href="~/">ASP.NET Web API</a></p>
            </div>
            <div class="float-right">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                        <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                    </ul>
                </nav>
            </div>
        </div>
    </header>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>